### ISSUE TITLE
How to use AzureOpenAI instead of OpenAI

### ISSUE THREAD

**Issue by Major-wagh** [OpenBMB/RepoAgent#62]
Hello, I loved the project and its workflow

I wanted to use AzureOpenAI instead of OpenAi. Can you please explain the process and template code for the same.

**Comment by LOGIC-10** [comment]
I think it goes like this:

python```
client = AzureOpenAI(
    api_key="",
    azure_endpoint="",
    api_version= "2023-09-01-preview",
)
```

simply replace client = OpenAI in the chatEngine.py file.

**Comment by Umpire2018** [comment]
<img width="571" alt="image" src="https://github.com/OpenBMB/RepoAgent/assets/138990495/1490d5f3-d193-47ab-b71c-06e8888d1280">

Sorry for late reply, you need to modify `repo_agent/chat_engine.py` to

1.  Replace `from openai import APIConnectionError, OpenAI` with `from openai import APIConnectionError, AzureOpenAI`

2.  `line 72-76`, replace
```python
        client = OpenAI(
            api_key=setting.chat_completion.openai_api_key.get_secret_value(),
            base_url=str(setting.chat_completion.base_url),
            timeout=setting.chat_completion.request_timeout,
        )
```

with

```python
        client = AzureOpenAI(
            api_key=setting.chat_completion.openai_api_key.get_secret_value(),
            api_version="place-your-api-version-here",
            azure_endpoint=str(setting.chat_completion.base_url),
            timeout=setting.chat_completion.request_timeout,
        
        )
```

In this way, you can still use `repoagent configure` to set `api_key` and `azure_endpoint`, but hardcode `api_version` .
3. 
```sh
pip uninstall repoagent
pdm install
```

4. Use `repoagnt run` as the same.

I believe this is the easiest way to use AzureOpenai` right now. We want to introduce a robust solution of multiple llms support which is not priority but we are welcome to collaboration.

Note: I have deleted a wrong comment in this issue.
